version: '3'

services:
  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    image: openspeedtest/latest
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.openspeedtest.rule=Host(`openspeedtest.site`)"
      - "traefik.http.routers.openspeedtest.entrypoints=https"
      - "traefik.http.routers.openspeedtest.tls=true"
      - "traefik.http.services.openspeedtest.loadbalancer.server.port=3001"
      - "traefik.http.routers.openspeedtest.tls.certresolver=letsEncrypt"

networks:
  proxy:
    external: true