version: '3'

services:
  minecraft:
    image: "marctv/minecraft-papermc-server:latest"
    restart: unless-stopped
    container_name: "minecraft"
    environment:
      MEMORYSIZE: "16G"
      PAPERMC_FLAGS: ""
    volumes:
      - "/home/admin/docker/minecraft:/data:rw"
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true