version: '3'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
      - VERSION=docker
      - PLEX_CLAIM=xxx
    volumes:
      - /home/admin/docker/plex:/config
      - /tv:/tv
      - /movies:/movies
    restart: unless-stopped