version: '3'

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    environment:
      - CF_API_EMAIL=xxx
      - CF_DNS_API_TOKEN=xxx
      - CF_ZONE_API_TOKEN=xxx
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/admin/docker/traefik-logs:/var/log/traefik
      - /home/admin/docker/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
  proxy:
    external: true